#!/bin/bash
#
# Find where a symbol is used in the nDPI source
#
# Usage: wndpi symbol

symbol=$1

for f in `find . -name "*.o"` ; do 
  if [ ! -z "`objdump -t $f | grep " ${symbol}" | grep UND`" ] ; then
    echo $f
  fi
done
